### ISSUE TITLE
Add support for the Aurorian Mod & Twilight Forest

### ISSUE THREAD

**Issue by vizthex123** [Laike-Endaril/Don-t-Even-Axe#1]
Could you do it?

**Comment by Laike-Endaril** [comment]
This mod was created and intended as a very simple drop-in workaround to rebalance vanilla axes and axes based on vanilla axes.  All it does is check if the mainhand item is an axe *tool*, and if so, halves damage from it.

I don't plan to expand this mod, because the only reasonable expansion would be a full-fledged item rebalancing mod, with configs that let you rebalance whatever items you want, and that would mean a mod rename.  So if I were to do it, it would be a new mod.  I'm a bit too busy to add any new mods to my workload right now.

As a workaround, Dynamic Stealth can actually do this already.  It has configs for altering attacks, with detailed item filter settings.  This is in DS because it has settings for stealth attacks as well as normal attacks.

A dedicated item rebalancing mod is not a bad idea, but I don't know if or when I'd get around to making it.

**Comment by xJon** [comment]
@Laike-Endaril Could you implement a simple blacklist* for this mod?
Any items that match the blacklist will not receive the damage changes; this could support other mods' axes which shouldn't be altered.

**Comment by Laike-Endaril** [comment]
I'm not going to expand this mod, but since I've gotten multiple requests...

[https://www.curseforge.com/minecraft/mc-mods/item-damage-rebalancer](https://www.curseforge.com/minecraft/mc-mods/item-damage-rebalancer)
